services:
    app.form.profile:
        class: AppUserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
            
    app.form.change_password:
        class: AppUserBundle\Form\PasswordType
        tags:
            - { name: form.type, alias: app_user_password }
            
    appuserbundle.user_manipulator:
        class: AppUserBundle\Util\UserManipulator
        arguments: [ "@fos_user.user_manager" ]
