language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  
cache: apt

env:
    global:
        - SYMFONY_ENV=test
        - COMPOSER_DISABLE_XDEBUG_WARN=1

before_script:
  - composer install -n -o

  - echo 'date.timezone = America/Vancouver' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./vendor/bin/phpunit
