nines_blog:
    resource: "@NinesBlogBundle/Controller"
    type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

nines_user:
    resource: "@UserBundle/Controller/"
    type: annotation

feedback:
    resource: "@FeedbackBundle/Controller/"
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
