app:
    resource: "@AppBundle/Controller/"
    type:     annotation

appuser:
    resource: "@AppUserBundle/Controller/"
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
