# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
    app.form.firm_filter:
        class: AppBundle\Form\FirmFilterType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }

    app.form.title_filter:
        class: AppBundle\Form\TitleFilterType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }

    app.form.person_filter:
        class: AppBundle\Form\PersonFilterType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }

