services:
    feedback.comment:
        class: FeedbackBundle\Services\CommentService
        arguments: [ "%feedback.routing%" ]
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
            - [ setRouter, ["@router"]]
